// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentElectricCar.API.Contexts;

namespace RentElectricCar.API.Migrations
{
    [DbContext(typeof(RentACarDbContext))]
    partial class RentACarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RentElectricCar.API.Entities.Car", b =>
                {
                    b.Property<Guid>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MileAge")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ProductionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CarId");

                    b.HasIndex("LocationId");

                    b.ToTable("CarsForRent");

                    b.HasData(
                        new
                        {
                            CarId = new Guid("b70385e1-11dc-4fe5-ad0a-f40000d8cde8"),
                            ColorName = "Red",
                            LocationId = new Guid("404a9219-6a83-43ef-9a2d-0f7891a6db50"),
                            MileAge = 50000,
                            NumberOfDoors = 5,
                            NumberOfSeats = 5,
                            ProductionDate = new DateTimeOffset(new DateTime(2020, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Automatic"
                        },
                        new
                        {
                            CarId = new Guid("3da18906-b85d-4460-bcef-42da4bffdb35"),
                            ColorName = "White",
                            LocationId = new Guid("404a9219-6a83-43ef-9a2d-0f7891a6db50"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("e8078e7c-2cf4-4f51-9061-5208686e221c"),
                            ColorName = "White",
                            LocationId = new Guid("07f456ff-0e3e-4d4c-a82c-a5ffb58d2835"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("343f6f78-2a8f-43d7-abc9-9e9b5770e9c4"),
                            ColorName = "White",
                            LocationId = new Guid("777b5fbf-726b-46f7-83c0-fc2e1cea39ce"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("fc9e4cf3-5e29-499e-b295-16f763a8007d"),
                            ColorName = "White",
                            LocationId = new Guid("07f456ff-0e3e-4d4c-a82c-a5ffb58d2835"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("5edacdd9-5016-4b21-bcf2-d16723cd8a67"),
                            ColorName = "White",
                            LocationId = new Guid("737fe335-bbcc-42b3-b43a-1ac4ca446ef1"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("3df9d369-2055-4340-92d9-cf69a554474c"),
                            ColorName = "White",
                            LocationId = new Guid("737fe335-bbcc-42b3-b43a-1ac4ca446ef1"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("4c2b1a41-8b3f-4e9c-a582-61a978a56559"),
                            ColorName = "White",
                            LocationId = new Guid("737fe335-bbcc-42b3-b43a-1ac4ca446ef1"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("a75e94b7-94dc-4805-bfd0-a88edd2aee33"),
                            ColorName = "White",
                            LocationId = new Guid("737fe335-bbcc-42b3-b43a-1ac4ca446ef1"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("9f6a4609-27b3-446f-886c-2280677217b7"),
                            ColorName = "White",
                            LocationId = new Guid("07f456ff-0e3e-4d4c-a82c-a5ffb58d2835"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("d9cbf395-9a6c-4e95-a823-7ecaf8c6f044"),
                            ColorName = "White",
                            LocationId = new Guid("07f456ff-0e3e-4d4c-a82c-a5ffb58d2835"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("3f977feb-7832-4153-bc1a-c1f0ba6a9d62"),
                            ColorName = "White",
                            LocationId = new Guid("d224be3e-e9c1-44a6-a262-a2e422ecdf5a"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("0efbfce9-72cb-40a5-b9e6-8a8f5d6e68a9"),
                            ColorName = "White",
                            LocationId = new Guid("d224be3e-e9c1-44a6-a262-a2e422ecdf5a"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("65ceb99b-ebc8-45fa-a940-f22240db9a2d"),
                            ColorName = "White",
                            LocationId = new Guid("d224be3e-e9c1-44a6-a262-a2e422ecdf5a"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("42d021c4-5234-438d-a32f-c322614b0bd1"),
                            ColorName = "White",
                            LocationId = new Guid("d224be3e-e9c1-44a6-a262-a2e422ecdf5a"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("0b38b8c2-4396-4e6f-aebe-3189f2392d76"),
                            ColorName = "White",
                            LocationId = new Guid("ba22a556-afd4-4d71-a1a6-0997775308bc"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("b54af349-0df6-4a3c-8cea-359ee837a93c"),
                            ColorName = "White",
                            LocationId = new Guid("ba22a556-afd4-4d71-a1a6-0997775308bc"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("5d71036f-fe63-4dd1-bfa0-efbebd16d076"),
                            ColorName = "White",
                            LocationId = new Guid("f90a1aaa-4360-4419-848e-47cf740cbc88"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("cd94eecf-ab12-43e9-929b-d91f25a01e7b"),
                            ColorName = "White",
                            LocationId = new Guid("d224be3e-e9c1-44a6-a262-a2e422ecdf5a"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("f8e70fe1-fa05-436c-86b6-0687b8fbdc9b"),
                            ColorName = "White",
                            LocationId = new Guid("8d5e3909-3785-4d7a-bde9-103aefd9f163"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("42089e62-f387-4f49-a6a9-e77703d3da2e"),
                            ColorName = "White",
                            LocationId = new Guid("886d8a9c-5f25-44c5-a8c8-b2921afad367"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("bc5f4c8d-15bc-41c6-b4b6-d70fcb6cfef8"),
                            ColorName = "White",
                            LocationId = new Guid("886d8a9c-5f25-44c5-a8c8-b2921afad367"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("1ada923e-3301-4701-9114-60c01e8b9aaa"),
                            ColorName = "White",
                            LocationId = new Guid("f0f3c209-1afb-4d77-a1e4-41b980bbc39c"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("7972dbd1-c454-4d5d-b82a-0457212fde65"),
                            ColorName = "White",
                            LocationId = new Guid("0179ab63-376f-47bc-a1e0-b7939aeeca26"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("80ec6757-b48d-40b0-9084-e97e5922e34f"),
                            ColorName = "White",
                            LocationId = new Guid("0179ab63-376f-47bc-a1e0-b7939aeeca26"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("eeb58d0d-9660-43e1-a6b2-985ee824b237"),
                            ColorName = "White",
                            LocationId = new Guid("65cb8f32-5444-4fd4-b816-8f57cde20e18"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("daa0dabb-9393-4fd4-9aef-7de5771e6713"),
                            ColorName = "White",
                            LocationId = new Guid("8a603c82-7c0b-4de9-bdcd-db669cf48c06"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("2974486c-389e-4ae0-a214-aecc587aa260"),
                            ColorName = "White",
                            LocationId = new Guid("8a603c82-7c0b-4de9-bdcd-db669cf48c06"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("76c472d8-996a-477f-b1f3-e736ef5a0220"),
                            ColorName = "White",
                            LocationId = new Guid("8a603c82-7c0b-4de9-bdcd-db669cf48c06"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("cbeee778-bb1e-4cbc-9709-81924db54ba7"),
                            ColorName = "White",
                            LocationId = new Guid("8a603c82-7c0b-4de9-bdcd-db669cf48c06"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("447601c1-ee69-44bd-850d-4d1507e773f0"),
                            ColorName = "White",
                            LocationId = new Guid("8a603c82-7c0b-4de9-bdcd-db669cf48c06"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("7045b787-a166-437a-b823-9dc98ab7c8f8"),
                            ColorName = "White",
                            LocationId = new Guid("f4a9d00d-d7d2-46f5-a53a-b5a5e250244b"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("bb30470f-499e-435c-a581-c56fbbf211c6"),
                            ColorName = "White",
                            LocationId = new Guid("f4a9d00d-d7d2-46f5-a53a-b5a5e250244b"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("9abd8ad5-1a74-471c-a7fc-38ac79211ac3"),
                            ColorName = "White",
                            LocationId = new Guid("f4a9d00d-d7d2-46f5-a53a-b5a5e250244b"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("20a74c41-24f0-4ead-b8b2-b451f08c5395"),
                            ColorName = "White",
                            LocationId = new Guid("f4a9d00d-d7d2-46f5-a53a-b5a5e250244b"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("7f8c99fc-a33a-4bc8-b6b9-628e19ba4d92"),
                            ColorName = "White",
                            LocationId = new Guid("f4a9d00d-d7d2-46f5-a53a-b5a5e250244b"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("8c715de0-3acf-4411-bec5-d4b26646b75a"),
                            ColorName = "White",
                            LocationId = new Guid("f4a9d00d-d7d2-46f5-a53a-b5a5e250244b"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("c8630eb7-b18a-49d1-b465-14d72cd6fc78"),
                            ColorName = "White",
                            LocationId = new Guid("1b05e9f4-eacf-4edd-aea0-3b1ab0efe524"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("f9324aff-8e36-463c-99cb-f675e2b278de"),
                            ColorName = "White",
                            LocationId = new Guid("1b05e9f4-eacf-4edd-aea0-3b1ab0efe524"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("635f8aaa-7ff9-4c6c-85c6-bed990651756"),
                            ColorName = "White",
                            LocationId = new Guid("1b05e9f4-eacf-4edd-aea0-3b1ab0efe524"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("f413bc87-dba6-4b6f-a1be-11db04ba486b"),
                            ColorName = "White",
                            LocationId = new Guid("1b05e9f4-eacf-4edd-aea0-3b1ab0efe524"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("9228fe18-c4e5-41ff-856a-72e10a2bb660"),
                            ColorName = "White",
                            LocationId = new Guid("1b05e9f4-eacf-4edd-aea0-3b1ab0efe524"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("7b8d50c0-3c05-486b-95dc-ed2a86d45b32"),
                            ColorName = "White",
                            LocationId = new Guid("8735b362-158f-48cc-ba5f-351a87add184"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("bffeb255-364f-4aef-a064-65948310e41a"),
                            ColorName = "White",
                            LocationId = new Guid("8735b362-158f-48cc-ba5f-351a87add184"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("fcfdf941-6040-48d1-bc0d-d2c161a2fca7"),
                            ColorName = "White",
                            LocationId = new Guid("8735b362-158f-48cc-ba5f-351a87add184"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("7fbd52e5-5552-4256-bd7c-e91561645360"),
                            ColorName = "White",
                            LocationId = new Guid("fabac37b-9c3b-452d-8626-272be26bdecd"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("58a34157-6a7d-4910-8f57-a22cbb89fa04"),
                            ColorName = "White",
                            LocationId = new Guid("fabac37b-9c3b-452d-8626-272be26bdecd"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("87ffb445-c2c7-4959-96e4-2f76b71e47ae"),
                            ColorName = "White",
                            LocationId = new Guid("27a1a764-db3d-478f-bbc3-190bbf93a5e7"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("6c578e04-8695-412e-b6c5-45441849e813"),
                            ColorName = "White",
                            LocationId = new Guid("27a1a764-db3d-478f-bbc3-190bbf93a5e7"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("8259c931-f342-4357-8075-022426ce6d0a"),
                            ColorName = "White",
                            LocationId = new Guid("27a1a764-db3d-478f-bbc3-190bbf93a5e7"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("e58fd46c-7fe6-42f4-b95b-65de84f19621"),
                            ColorName = "White",
                            LocationId = new Guid("27a1a764-db3d-478f-bbc3-190bbf93a5e7"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("ca75441a-6c47-4bfd-9e4f-723b9e0628cb"),
                            ColorName = "White",
                            LocationId = new Guid("27a1a764-db3d-478f-bbc3-190bbf93a5e7"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("e9dc0145-80a4-4d17-a076-c6cbe308ec1e"),
                            ColorName = "White",
                            LocationId = new Guid("27a1a764-db3d-478f-bbc3-190bbf93a5e7"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("db2bc9f2-dc58-4f17-b30c-4f8ba79b572e"),
                            ColorName = "White",
                            LocationId = new Guid("6ac8b9de-17ca-4d42-90f4-fd3b5c64774c"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("f7c8bbf7-92bc-437d-a27a-d60dd6c95f05"),
                            ColorName = "White",
                            LocationId = new Guid("6ac8b9de-17ca-4d42-90f4-fd3b5c64774c"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("75ad0206-5023-4a07-8744-af0def953ea6"),
                            ColorName = "White",
                            LocationId = new Guid("ae71ff9e-c117-4fa4-a431-4a3af7680a6b"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        },
                        new
                        {
                            CarId = new Guid("181d0d91-debc-45ae-86df-796f4f6f2338"),
                            ColorName = "White",
                            LocationId = new Guid("6ac8b9de-17ca-4d42-90f4-fd3b5c64774c"),
                            MileAge = 86000,
                            NumberOfDoors = 3,
                            NumberOfSeats = 2,
                            ProductionDate = new DateTimeOffset(new DateTime(2018, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Transmission = "Manual"
                        });
                });

            modelBuilder.Entity("RentElectricCar.API.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = new Guid("07f456ff-0e3e-4d4c-a82c-a5ffb58d2835"),
                            CityName = "Lappeenranta",
                            RegionName = "South Karelia"
                        },
                        new
                        {
                            LocationId = new Guid("777b5fbf-726b-46f7-83c0-fc2e1cea39ce"),
                            CityName = "Imatra",
                            RegionName = "South Karelia"
                        },
                        new
                        {
                            LocationId = new Guid("737fe335-bbcc-42b3-b43a-1ac4ca446ef1"),
                            CityName = "Jyväskylä",
                            RegionName = "Central Finland"
                        },
                        new
                        {
                            LocationId = new Guid("ba22a556-afd4-4d71-a1a6-0997775308bc"),
                            CityName = "Jämsä",
                            RegionName = "Central Finland"
                        },
                        new
                        {
                            LocationId = new Guid("f90a1aaa-4360-4419-848e-47cf740cbc88"),
                            CityName = "Laukaa",
                            RegionName = "Central Finland"
                        },
                        new
                        {
                            LocationId = new Guid("d224be3e-e9c1-44a6-a262-a2e422ecdf5a"),
                            CityName = "Tampere",
                            RegionName = "Pirkanmaa"
                        },
                        new
                        {
                            LocationId = new Guid("8d5e3909-3785-4d7a-bde9-103aefd9f163"),
                            CityName = "Ylöjärvi",
                            RegionName = "Pirkanmaa"
                        },
                        new
                        {
                            LocationId = new Guid("886d8a9c-5f25-44c5-a8c8-b2921afad367"),
                            CityName = "Nokia",
                            RegionName = "Pirkanmaa"
                        },
                        new
                        {
                            LocationId = new Guid("f0f3c209-1afb-4d77-a1e4-41b980bbc39c"),
                            CityName = "Kangasala",
                            RegionName = "Pirkanmaa"
                        },
                        new
                        {
                            LocationId = new Guid("0179ab63-376f-47bc-a1e0-b7939aeeca26"),
                            CityName = "Kotka",
                            RegionName = "Kymenlaakso"
                        },
                        new
                        {
                            LocationId = new Guid("65cb8f32-5444-4fd4-b816-8f57cde20e18"),
                            CityName = "Kouvola",
                            RegionName = "Kymenlaakso"
                        },
                        new
                        {
                            LocationId = new Guid("8a603c82-7c0b-4de9-bdcd-db669cf48c06"),
                            CityName = "Helsinki",
                            RegionName = "Uusimaa"
                        },
                        new
                        {
                            LocationId = new Guid("f4a9d00d-d7d2-46f5-a53a-b5a5e250244b"),
                            CityName = "Espoo",
                            RegionName = "Uusimaa"
                        },
                        new
                        {
                            LocationId = new Guid("1b05e9f4-eacf-4edd-aea0-3b1ab0efe524"),
                            CityName = "Vantaa",
                            RegionName = "Uusimaa"
                        },
                        new
                        {
                            LocationId = new Guid("8735b362-158f-48cc-ba5f-351a87add184"),
                            CityName = "Porvoo",
                            RegionName = "Uusimaa"
                        },
                        new
                        {
                            LocationId = new Guid("fabac37b-9c3b-452d-8626-272be26bdecd"),
                            CityName = "Lohja",
                            RegionName = "Uusimaa"
                        },
                        new
                        {
                            LocationId = new Guid("27a1a764-db3d-478f-bbc3-190bbf93a5e7"),
                            CityName = "Turku",
                            RegionName = "Southwest Finland"
                        },
                        new
                        {
                            LocationId = new Guid("6ac8b9de-17ca-4d42-90f4-fd3b5c64774c"),
                            CityName = "Salo",
                            RegionName = "Southwest Finland"
                        },
                        new
                        {
                            LocationId = new Guid("ae71ff9e-c117-4fa4-a431-4a3af7680a6b"),
                            CityName = "Kaarina",
                            RegionName = "Southwest Finland"
                        },
                        new
                        {
                            LocationId = new Guid("404a9219-6a83-43ef-9a2d-0f7891a6db50"),
                            CityName = "Rovaniemi",
                            RegionName = "Lapland"
                        });
                });

            modelBuilder.Entity("RentElectricCar.API.Entities.Car", b =>
                {
                    b.HasOne("RentElectricCar.API.Entities.Location", "Location")
                        .WithMany("Cars")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RentElectricCar.API.Entities.Location", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
